### ISSUE TITLE
部分painting文件夹与舰船code不对应 部分舰船不存在对应的painting文件夹

### ISSUE THREAD

**Issue by WardonNE** [Pelom777/AzurLaneTools#5]
以下为不对应的code与实际的文件夹
'hamanii' => 'hamanII',
'hamanii_2' => 'hamanII_2',
'yuekechengii_2' => 'yuekechengII_2',
'dahuangfengii' => 'dahuangfengII',
'dahuangfengii_2' => 'dahuangfengII_2',
'lanliii' => 'lanliII',
'lanliii_2' => 'lanliII_2',
'i25' => 'I25',
'i25_2' => 'I25_2',
'i56' => 'I56',
'i168' => 'I168',
'i168_2' => 'I168_2',
'hdn101' => 'HDN101',
'hdn201' => 'HDN201',
'hdn301' => 'HDN301',
'hdn401' => 'HDN401',
'hdn102_1' => 'HDN102_1',
'hdn102_2' => 'HDN102_2',
'hdn202_1' => 'HDN202_1',
'hdn202_2' => 'HDN202_2',
'hdn302_1' => 'HDN302_1',
'hdn302_2' => 'HDN302_2',
'hdn402_1' => 'HDN402_1',
'hdn402_2' => 'HDN402_2',

以下为不存在文件夹的code
'muyue_g',
'jiangfeng_2',
'xiaoyue',
'luao',
'i58',
'z25',
'z35',
'u557',

**Comment by Pelom777** [comment]
已修复
游戏内命名不规范，本项目中选择全部转为小写，但由于git for Windows不区分大小写而出现错误
